Repository pagopa/github-actions-template, pull requests merged in 2023-03, with the labels that each got.

#7 feat: Completed Aks Blueprint helm deploy
  aks-blueprint-helm-deploy/README.md
  aks-blueprint-helm-deploy/action.yml
Labels: size/small

#6 chore: Maven version beta
  maven-release/README.md
  maven-release/action.yml
  maven-semver/README.md
  maven-semver/action.yml
Labels: enhancement

#5 fix: Removed unused input
  ghcr-build-push/README.md
  ghcr-build-push/action.yml
Labels: size/small, patch
